name = "pace-radar-api"
main = "src/index.ts"
compatibility_date = "2026-08-31"

[[d1_databases]]
binding = "DB"
database_name = "pace-radar-db"
database_id = "d29a9a1a-b940-49a6-b45f-a5a22d163414"
migrations_dir = "../../migrations"
